# Site settings
title: Ragav Venkatesan
email: ragav.venkatesan@gmail.com
description: Venkatesan is a scientist at Amazon specializing in machine learning. 
url: https://ragavvenkatesan.github.io
github_username:  ragavvenkatesan
# Build settings
markdown: kramdown
