# Site settings
title: Ragav Venkatesan
email: email@ragav.net
description: Venkatesan is a scientist at Amazon specializing in machine learning. 
url: http://www.ragav.net
github_username:  ragavvenkatesan
# Build settings
markdown: kramdown
