# Site settings
title: Ragav Venkatesan
email: email@tagav.net
description: Venkatesan is a research scientist at Amazon Web Services specializing in computer vision and machine learning. 
url: http://www.ragav.net
github_username:  ragavvenkatesan
# Build settings
markdown: kramdown
